import { PropertyType } from '@/types';
import Colors, { PropertyTypeColors } from './Colors';

export interface Category {
  id: PropertyType;
  name: string;
  icon: string;
  color: string;
  description: string;
}

export const PropertyCategories: Category[] = [
  {
    id: 'house',
    name: 'Maisons',
    icon: '🏠',
    color: PropertyTypeColors.house,
    description: 'Maisons individuelles et villas',
  },
  {
    id: 'apartment',
    name: 'Appartements',
    icon: '🏢',
    color: PropertyTypeColors.apartment,
    description: 'Appartements et studios',
  },
  {
    id: 'land',
    name: 'Parcelles',
    icon: '📍',
    color: PropertyTypeColors.land,
    description: 'Terrains et parcelles',
  },
  {
    id: 'restaurant',
    name: 'Restaurants',
    icon: '🍽️',
    color: PropertyTypeColors.restaurant,
    description: 'Restaurants et bars',
  },
  {
    id: 'event-space',
    name: 'Salles de fête',
    icon: '🎉',
    color: PropertyTypeColors['event-space'],
    description: 'Salles pour événements',
  },
  {
    id: 'gym',
    name: 'Salles de sport',
    icon: '🏋️',
    color: PropertyTypeColors.gym,
    description: 'Salles de sport et fitness',
  },
  {
    id: 'supermarket',
    name: 'Supermarchés',
    icon: '🛒',
    color: PropertyTypeColors.supermarket,
    description: 'Supermarchés',
  },
  {
    id: 'phone',
    name: 'Téléphones', 
    icon: '📱',
    color: PropertyTypeColors.phone,
    description: 'Téléphones et smartphones',
  },
  {
    id: 'clothing-men',
    name: 'Vêtements Homme',
    icon: '👔',
    color: PropertyTypeColors['clothing-men'],
    description: 'Vêtements pour hommes',
  },
  {
    id: 'clothing-women',
    name: 'Vêtements Femme',
    icon: '👗',
    color: PropertyTypeColors['clothing-women'],
    description: 'Vêtements pour femmes',
  },
  {
    id: 'clothing-children',
    name: 'Vêtements Enfants',
    icon: '👶',
    color: PropertyTypeColors['clothing-children'],
    description: 'Vêtements pour enfants',
  },
  {
    id: 'shoes-men',
    name: 'Chaussures Homme',
    icon: '👞',
    color: PropertyTypeColors['shoes-men'],
    description: 'Chaussures pour hommes',
  },
  {
    id: 'shoes-women',
    name: 'Chaussures Femme',
    icon: '👠',
    color: PropertyTypeColors['shoes-women'],
    description: 'Chaussures pour femmes',
  },
  {
    id: 'shoes-children',
    name: 'Chaussures Enfants',
    icon: '👟',
    color: PropertyTypeColors['shoes-children'],
    description: 'Chaussures pour enfants',
  },
  {
    id: 'belt',
    name: 'Ceinture',
    icon: '🪢',
    color: PropertyTypeColors.belt,
    description: 'Ceintures et accessoires de ceinture',
  },
  {
    id: 'jacket',
    name: 'Jacket',
    icon: '🧥',
    color: PropertyTypeColors.jacket,
    description: 'Jackets et vestes chaudes',
  },
  {
    id: 'vest',
    name: 'Veste',
    icon: '👕',
    color: PropertyTypeColors.vest,
    description: 'Vestes et chemises de travail',
  },
  {
    id: 'hat',
    name: 'Chapeau',
    icon: '🎩',
    color: PropertyTypeColors.hat,
    description: 'Chapeaux et accessoires de tête',
  },  
  {
    id: 'earphones',
    name: 'Écouteurs',
    icon: '🎧',
    color: PropertyTypeColors.earphones,
    description: 'Écouteurs et casques audio',
  },
  {
    id: 'charger',
    name: 'Chargeur',
    icon: '🔌',
    color: PropertyTypeColors.charger,
    description: 'Chargeurs et accessoires de chargement',
  },
  {
    id: 'power-bank',
    name: 'Power Bank',
    icon: '🔋',
    color: PropertyTypeColors['power-bank'],
    description: 'Power Banks et batteries externes',
  },
  {
    id: 'phone-accessories',
    name: 'Accessoires Téléphone',
    icon: '📱',
    color: PropertyTypeColors['phone-accessories'],
    description: 'Accessoires pour téléphones',
  },
];

export const PropertyTypeNames: Record<PropertyType, string> = {
  house: 'Maison',
  apartment: 'Appartement',
  land: 'Parcelle',
  restaurant: 'Restaurant',
  'event-space': 'Salle de fête',
  gym: 'Salle Sport',
  supermarket: 'Supermarché',
  phone: 'Téléphone',
  'clothing-men': 'Vêtements Homme',
  'clothing-women': 'Vêtements Femme',
  'clothing-children': 'Vêtements Enfants',
  'shoes-men': 'Chaussures Homme',
  'shoes-women': 'Chaussures Femme',
  'shoes-children': 'Chaussures Enfants',
  belt: 'Ceinture',
  jacket: 'Jacket',
  vest: 'Veste',
  hat: 'Chapeau',
  earphones: 'Écouteurs',
  charger: 'Chargeur',
  'power-bank': 'Power Bank',
  'phone-accessories': 'Accessoires Téléphone',
  computer: 'Ordinateur',
  fridge: 'Frigo',
  freezer: 'Congélateur',
  shelf: 'Étagère',
  sofa: 'Canapé',
  fer: 'Fer',
  fruitier: 'Fruitier',
  'washing-machine': 'Machine à laver',
  'other-products': 'Autres Produits',
};

// Mapping des attributs spécifiques par catégorie
export const CategoryAttributes: Record<PropertyType, string[]> = {
  house: [],
  apartment: [],
  land: [],
  restaurant: [],
  'event-space': [],
  gym: [],
  supermarket: [],
  'power-bank': [],
  'phone': ['marque', 'couleur'],
  'clothing-men': ['type', 'taille', 'couleur'],
  'clothing-women': ['type', 'taille', 'couleur'],
  'clothing-children': ['type', 'taille', 'couleur'],
  'shoes-men': ['pointure', 'couleur'],
  'shoes-women': ['pointure', 'couleur'],
  'shoes-children': ['pointure', 'couleur'],
  'belt': ['taille', 'couleur'],
  'jacket': ['taille', 'couleur'],
  'vest': ['taille', 'couleur'],
  'hat': ['taille', 'couleur'],
  'earphones': ['marque', 'couleur'],
  'charger': ['marque', 'couleur'],
  'phone-accessories': ['type', 'marque', 'couleur'],
  'computer': ['marque', 'couleur'],
  'fridge': ['marque', 'couleur'],
  'freezer': ['marque', 'couleur'],
  'shelf': ['taille', 'couleur'],
  'sofa': ['taille', 'couleur'],
  'fer': ['marque', 'couleur'],
  'fruitier': ['type', 'taille', 'couleur'],
  'washing-machine': ['marque', 'couleur'],
  'other-products': ['type', 'marque', 'couleur'],
  
};
