import { Agent, Conversation, Message } from '@/types';

export const MOCK_AGENTS: Agent[] = [
  {
    id: '1',
    name: 'Amadou Sow',
    phone: '+221 77 123 45 67',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amadou',
    email: 'amadou.sow@realestate.com',
  },
  {
    id: '2',
    name: 'Marie Diallo',
    phone: '+221 78 987 65 43',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marie',
    email: 'marie.diallo@realestate.com',
  },
  {
    id: '3',
    name: 'Jean Kouassi',
    phone: '+225 07 123 45 67',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jean',
    email: 'jean.kouassi@realestate.com',
  },
  {
    id: '4',
    name: 'Kofi Mensah',
    phone: '+233 24 123 45 67',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kofi',
    email: 'kofi.mensah@realestate.com',
  },
  {
    id: '5',
    name: 'Chioma Okafor',
    phone: '+234 81 123 45 67',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chioma',
    email: 'chioma.okafor@realestate.com',
  },
  {
    id: '6',
    name: 'Aïssatou Ba',
    phone: '+226 76 123 45 67',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aissatou',
    email: 'aissatou.ba@realestate.com',
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv1',
    agentId: '1',
    agent: MOCK_AGENTS[0],
    propertyId: '1',
    propertyTitle: 'Villa moderne à Dakar',
    messages: [
      {
        id: '1',
        conversationId: 'conv1',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Bonjour, je suis intéressé par la villa moderne',
        timestamp: '14:30',
        isUser: true,
      },
      {
        id: '2',
        conversationId: 'conv1',
        senderId: '1',
        senderName: 'Amadou Sow',
        text: 'Bonjour! Merci de votre intérêt. La villa est disponible pour une visite dès maintenant.',
        timestamp: '14:32',
        isUser: false,
      },
      {
        id: '3',
        conversationId: 'conv1',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Quand puis-je la visiter?',
        timestamp: '14:35',
        isUser: true,
      },
      {
        id: '4',
        conversationId: 'conv1',
        senderId: '1',
        senderName: 'Amadou Sow',
        text: 'Vous pouvez venir demain à 10h ou 14h. Laquelle vous convient?',
        timestamp: '14:37',
        isUser: false,
      },
    ],
    lastMessage: 'Vous pouvez venir demain à 10h ou 14h. Laquelle vous convient?',
    lastMessageTime: '14:37',
  },
  {
    id: 'conv2',
    agentId: '2',
    agent: MOCK_AGENTS[1],
    propertyId: '2',
    propertyTitle: 'Appartement spacieux en centre-ville',
    messages: [
      {
        id: '1',
        conversationId: 'conv2',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Bonjour, je cherche un appartement spacieux',
        timestamp: '10:15',
        isUser: true,
      },
      {
        id: '2',
        conversationId: 'conv2',
        senderId: '2',
        senderName: 'Marie Diallo',
        text: 'Bonjour! J\'ai exactement ce qu\'il vous faut. Cet appartement est parfait!',
        timestamp: '10:18',
        isUser: false,
      },
      {
        id: '3',
        conversationId: 'conv2',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Quel est le prix exact?',
        timestamp: '10:20',
        isUser: true,
      },
      {
        id: '4',
        conversationId: 'conv2',
        senderId: '2',
        senderName: 'Marie Diallo',
        text: '$2,500/mois avec un contrat de 12 mois. Très bien situé!',
        timestamp: '10:22',
        isUser: false,
      },
      {
        id: '5',
        conversationId: 'conv2',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Je suis très intéressé',
        timestamp: '10:25',
        isUser: true,
      },
    ],
    lastMessage: 'Je suis très intéressé',
    lastMessageTime: '10:25',
  },
  {
    id: 'conv3',
    agentId: '3',
    agent: MOCK_AGENTS[2],
    propertyId: '3',
    propertyTitle: 'Parcelle en zone résidentielle',
    messages: [
      {
        id: '1',
        conversationId: 'conv3',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Avez-vous des parcelles disponibles?',
        timestamp: '09:00',
        isUser: true,
      },
      {
        id: '2',
        conversationId: 'conv3',
        senderId: '3',
        senderName: 'Jean Kouassi',
        text: 'Oui, j\'ai plusieurs parcelles magnifiques en zone résidentielle',
        timestamp: '09:05',
        isUser: false,
      },
    ],
    lastMessage: 'Oui, j\'ai plusieurs parcelles magnifiques en zone résidentielle',
    lastMessageTime: '09:05',
  },
  {
    id: 'conv4',
    agentId: '4',
    agent: MOCK_AGENTS[3],
    propertyId: '4',
    propertyTitle: 'Restaurant avec cuisine équipée',
    messages: [
      {
        id: '1',
        conversationId: 'conv4',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Bonjour, j\'aimerais en savoir plus sur le restaurant',
        timestamp: '15:45',
        isUser: true,
      },
      {
        id: '2',
        conversationId: 'conv4',
        senderId: '4',
        senderName: 'Kofi Mensah',
        text: 'Bien sûr! C\'est un excellent établissement avec tous les équipements modernes',
        timestamp: '15:48',
        isUser: false,
      },
    ],
    lastMessage: 'Bien sûr! C\'est un excellent établissement avec tous les équipements modernes',
    lastMessageTime: '15:48',
  },
  {
    id: 'conv5',
    agentId: '5',
    agent: MOCK_AGENTS[4],
    propertyId: '5',
    propertyTitle: 'Salle de sport moderne',
    messages: [
      {
        id: '1',
        conversationId: 'conv5',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Quelles sont les dimensions de la salle?',
        timestamp: '11:30',
        isUser: true,
      },
      {
        id: '2',
        conversationId: 'conv5',
        senderId: '5',
        senderName: 'Chioma Okafor',
        text: 'La salle fait 2000m² avec des équipements de dernière génération',
        timestamp: '11:33',
        isUser: false,
      },
    ],
    lastMessage: 'La salle fait 2000m² avec des équipements de dernière génération',
    lastMessageTime: '11:33',
  },
  {
    id: 'conv6',
    agentId: '6',
    agent: MOCK_AGENTS[5],
    propertyId: '7',
    propertyTitle: 'Supermarché en zone commerciale',
    messages: [
      {
        id: '1',
        conversationId: 'conv6',
        senderId: 'user',
        senderName: 'Vous',
        text: 'Quel est le flux de clients estimé par jour?',
        timestamp: '16:00',
        isUser: true,
      },
      {
        id: '2',
        conversationId: 'conv6',
        senderId: '6',
        senderName: 'Aïssatou Ba',
        text: 'Environ 500-600 clients par jour. C\'est une très bonne zone commerciale!',
        timestamp: '16:03',
        isUser: false,
      },
    ],
    lastMessage: 'Environ 500-600 clients par jour. C\'est une très bonne zone commerciale!',
    lastMessageTime: '16:03',
  },
];
